# Generated by Django 5.0.7 on 2024-08-15 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_ratings_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxValueValidator(1)], verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
