# Generated by Django 5.0.7 on 2024-08-22 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ')),
                ('size', models.IntegerField(verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'اطلاعات',
                'verbose_name_plural': 'لیست اطلاعات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Info', to='products.productinfo', verbose_name='اطلاعات کالا'),
        ),
    ]
